### ISSUE TITLE
Train FairMOT on custom data

### ISSUE THREAD

**Issue by Sarouch** [supperted825/FairMOT-X#1]
Hello,
Thank you for this repo, could you please make a Redme on custom data tracking ?
Thank you

**Comment by supperted825** [comment]
Hi Sarouch,

For now I will not be making a proper ReadMe as I am still testing and debugging the project. (Thus some things still don't work properly / might still change later on). If you are keen to develop further from the current state of the project, you can have a look in src/lib/datasets/yolomot.py, under the YOLOMOT class.

You will first need to prepare the paths of your data. There are many examples available in /src/data. You will then have to point to these with a config file (see /src/lib/cfg)

Your labels for each image should be a text file with the following per-line format.

class id, track id, normalised x, normalised y, normalised w, normalised h

**Comment by Sarouch** [comment]
Hi @supperted825,

Thank you for your quick answer.
I will try it soon.

Regards,
