### ISSUE TITLE
求共享生成训练数据的步骤和代码

### ISSUE THREAD

**Issue by wangweihq8707** [supperted825/FairMOT-X#12]
您好， 是否可以共享一下您的生成训练集的代码和步骤，我的邮箱：wangwei2022r@126.com

**Comment by ws-26-ws** [comment]
Hello, have you got the code and steps for generating training sets? If yes, can you send it to my email address? My email account is 2287167110@qq.com.

**Comment by supperted825** [comment]
For generating training / val set and labels, please refer to the steps described [here](https://github.com/dingwoai/FairMOT-BDD100K).
