### ISSUE TITLE
关于在fairmot框架中简易使用现有模型的问题

### ISSUE THREAD

**Issue by javalier** [supperted825/FairMOT-X#5]
目前基本所有的fairmot框架的检测网络都采用DCN结构，对于一些其他普遍性的检测网络，如何修改能够直接在fairmot上运行呢，比如最基础的resnet网络，我苦于无法将改进的网络结构应用在此框架之下。

**Comment by supperted825** [comment]
Hope you don't mind my reply in english:

DCN in FairMOT is usually used to replace the regular Conv2D layer during upsampling of backbone features. So, if you don't want to use DCN, you can just replace any DCN layer back with Conv2D. For example, the [resnet_dcn](https://github.com/CaptainEven/MCMOT/blob/a9080be804f00d6830f96e5d661df089eb799330/src/lib/models/networks/resnet_dcn.py#L236) here imports DCN but does not use it in the upsampling layer. This might be a good reference for you.

For my implementation of FairMOT, DCN is not used in the YOLOX detector at all. So you can modify the [featurefusor class](https://github.com/supperted825/FairMOT-X/blob/42ff726dfb1e19545f30d0a77039f323c663f919/src/lib/models/networks/yolox/yolo_head.py#L37) in the reID head to avoid DCN and see how it performs. Hope this helps.

**Comment by javalier** [comment]
谢谢,我就是想把resnet+attention添加到fairmot中,但是无法实现正确的生成模型,在你举例的网络resnet_dcn 260line 最后一个forward如果不使用x=self.deconv_layers(x),怎样才能返回合适的x,来生成model.(有些冒昧,谢谢你)

**Comment by supperted825** [comment]
Are you referring to how to get the upscaling to the correct heatmap size? The main layer that upsamples the features is the [ConvTranspose2D](https://github.com/CaptainEven/MCMOT/blob/a9080be804f00d6830f96e5d661df089eb799330/src/lib/models/networks/resnet_dcn.py#L239) layer with stride 2. It will basically 2x the image size.
