### ISSUE TITLE
how to train on other datasets

### ISSUE THREAD

**Issue by fafa114** [supperted825/FairMOT-X#6]
Hello !  First,thank you for your work!  But I have a question. I want to train on other datasets not bdd100k , such as detrac, how to use? Thank you very much!

**Comment by supperted825** [comment]
Hi @fafa114, please refer to https://github.com/supperted825/FairMOT-X/issues/1#issuecomment-977710712

**Comment by fafa114** [comment]
Thank you for your timely reply. I will try it as soon as possible，thank you！
